# Generated by Django 5.0 on 2025-11-23 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoCompleteRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "todoist_task_id",
                    models.CharField(
                        help_text="Todoist task ID to auto-complete",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "task_content",
                    models.CharField(
                        help_text="Task name (for reference)", max_length=500
                    ),
                ),
                (
                    "complete_after_hours",
                    models.IntegerField(
                        default=0,
                        help_text="Hours after due date to auto-complete (0 = immediately when overdue)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was auto-completed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autocomplete_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-Complete Rule",
                "verbose_name_plural": "Auto-Complete Rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_updated", "Task Updated"),
                            ("task_completed", "Task Completed"),
                            ("task_overdue", "Task Overdue"),
                            ("watcher_added", "Added as Watcher"),
                            ("comment_added", "Comment Added"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "todoist_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Related Todoist task ID (if applicable)",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (for reference)", max_length=255
                    ),
                ),
                (
                    "content_template",
                    models.CharField(
                        help_text="Task content with placeholders. Example: 'Weekly Report - {date}'",
                        max_length=500,
                    ),
                ),
                (
                    "description_template",
                    models.TextField(
                        blank=True, help_text="Task description template (optional)"
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        help_text="Todoist project ID (leave blank for Inbox)",
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Urgent")],
                        default=1,
                        help_text="Task priority (1-4)",
                    ),
                ),
                (
                    "labels",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated label names",
                        max_length=255,
                    ),
                ),
                (
                    "auto_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-complete this task after due date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to generate new tasks from this template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When was the last task generated from this template",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Template",
                "verbose_name_plural": "Task Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "todoist_task_id",
                    models.CharField(
                        help_text="ID of the generated Todoist task", max_length=50
                    ),
                ),
                ("task_content", models.CharField(max_length=500)),
                ("due_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_tasks",
                        to="tasks.tasktemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Task",
                "verbose_name_plural": "Generated Tasks",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskWatcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "todoist_task_id",
                    models.CharField(help_text="Todoist task ID", max_length=50),
                ),
                (
                    "task_content",
                    models.CharField(
                        help_text="Task name (cached for display)", max_length=500
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify_on_update",
                    models.BooleanField(
                        default=True, help_text="Notify watcher when task is updated"
                    ),
                ),
                (
                    "notify_on_complete",
                    models.BooleanField(
                        default=True, help_text="Notify watcher when task is completed"
                    ),
                ),
                (
                    "notify_on_overdue",
                    models.BooleanField(
                        default=True,
                        help_text="Notify watcher when task becomes overdue",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="User who added this watcher",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watcher",
                    models.ForeignKey(
                        help_text="User watching this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Watcher",
                "verbose_name_plural": "Task Watchers",
                "ordering": ["-added_at"],
                "unique_together": {("todoist_task_id", "watcher")},
            },
        ),
    ]
